DjangoUeditor3/DUSite/urls.py
#coding:utf-8
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
import settings
from django.contrib import admin
from TestApp.views import  TestUEditorModel,ajaxcmd,TestUEditor

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DUSite.views.home', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^test/$',TestUEditorModel),
    url(r'^test2/$',TestUEditor),
    url(r'^ajaxcmd/$',ajaxcmd)

)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
        url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
        url(r'^(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
    )

DjangoUeditor3/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

MxOnline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt
from django.views.static import serve
from MxOnline.settings import MEDIA_ROOT
from apps.user.views import LoginView, LogoutView, RegisterView, SendSmsView, DynamicLoginView, UserCenterView, \
    UserCenterMyCourseView, UserCenterMyMessageView

import xadmin

xadmin.autodiscover()

# version模块自动注册需要版本控制的 Model
from xadmin.plugins import xversion

xversion.register_models()

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name="index"),
    path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    path('login/', LoginView.as_view(), name="login"),
    path('d_login/', DynamicLoginView.as_view(), name="d_login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('send_sms/', csrf_exempt(SendSmsView.as_view()), name="send_sms"),
    url(r'^org/', include(('apps.organization.urls', 'organizations'), namespace='org')),
    url(r'^op/', include(('apps.operation.urls', 'operation'), namespace='op')),
    url(r'^course/', include(('apps.course.urls', 'course'), namespace='course')),
    url(r'^users/', include(('apps.user.urls', 'users'), namespace='users'))
]

apps/course/urls.py
from django.conf.urls import url
from apps.course.views import CourseListView, CourseDetailView, CourseLessonView, CourseVideoView, CourseCommentView

urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name='list'),
    url(r'^(?P<course_id>\d+)$', CourseDetailView.as_view(), name='detail'),
    url(r'^(?P<course_id>\d+)/lesson$', CourseLessonView.as_view(), name='lesson'),
    url(r'^(?P<course_id>\d+)/comment$', CourseCommentView.as_view(), name='comment'),
    url(r'^(?P<course_id>\d+)/video/(?P<video_id>\d+)$', CourseVideoView.as_view(), name='video'),
]

apps/organization/urls.py
from django.conf.urls import url, include
from apps.organization.views import OrgView, AddAskView, OrgHomeView, OrgTeacherView, OrgCourseView, OrgDescView, \
    TeachersView, TeacherDetailView

urlpatterns = [
    url(r'^list/$', OrgView.as_view(), name='list'),
    url(r'^add_ask/$', AddAskView.as_view(), name='add_ask'),
    # url(r'^add_ask/$', AddAskView.as_view(), name='add_ask'),
    url(r'^(?P<org_id>\d+)$', OrgHomeView.as_view(), name='home'),
    url(r'^(?P<org_id>\d+)/course/$', OrgCourseView.as_view(), name='course'),
    url(r'^(?P<org_id>\d+)/desc/$', OrgDescView.as_view(), name='desc'),
    url(r'^(?P<org_id>\d+)/teacher/$', OrgTeacherView.as_view(), name='teacher'),
    url(r'^teachers/$', TeachersView.as_view(), name='teachers'),
    url(r'^teachers/(?P<teacher_id>\d+)$', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/user/urls.py
from django.conf.urls import url
from django.urls import path
from apps.user.views import UserCenterView, UserCenterMyMessageView, UserCenterMyCourseView, UserCenterMyFavCourseiew, \
    UserCenterMyFavOrgView, UserCenterMyFavTeacherView, UserImgUpload

urlpatterns = [
    path('info/', UserCenterView.as_view(), name="info"),
    path('course/', UserCenterMyCourseView.as_view(), name="mycourse"),
    path('fav_course/', UserCenterMyFavCourseiew.as_view(), name="myfav_course"),
    path('fav_teacher/', UserCenterMyFavTeacherView.as_view(), name="myfav_teacher"),
    path('fav_org/', UserCenterMyFavOrgView.as_view(), name="myfav_org"),
    path('message/', UserCenterMyMessageView.as_view(), name="mymessage"),
    path('image/upload/', UserImgUpload.as_view(), name="user_img_upload"),
]

apps/course/models.py
from django.db import models
from apps.user.models import BaseModel
from apps.organization.models import CourseOrg, Teacher
from DjangoUeditor.models import UEditorField
from six import python_2_unicode_compatible


# Create your models here.

@python_2_unicode_compatible
class Course(BaseModel):
    DEGREE_CHOICE = (
        ('cj', '初级'),
        ('zj', '中级'),
        ('gj', '高级')
    )
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name='课程所属教师')
    course_org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, verbose_name='课程所属机构')
    name = models.CharField(verbose_name='课程名', max_length=50)
    desc = models.CharField(verbose_name='描述', max_length=300)
    learn_times = models.PositiveIntegerField(verbose_name='时长/分', default=0)
    degree = models.CharField(verbose_name='难度', choices=DEGREE_CHOICE, max_length=2)
    students = models.PositiveIntegerField(verbose_name='学习次数', default=0)
    fav_nums = models.PositiveIntegerField(verbose_name='收藏次数', default=0)
    click_nums = models.PositiveIntegerField(verbose_name='点击数', default=0)
    notice = models.CharField(verbose_name='课程公告', max_length=300, default='')
    category = models.CharField(verbose_name='类别', max_length=20, default=u'后端开发')
    tag = models.CharField(verbose_name='标签', max_length=10, default='')
    youneed_know = models.CharField(verbose_name='课程须知', max_length=300, default='')
    teacher_tell = models.CharField(verbose_name='老师告诉你', max_length=300, default='')
    is_classics = models.BooleanField(verbose_name='是否经典', default=False)
    detail = UEditorField(u'课程详情', width=600, height=300, toolbars='full', imagePath='courses/ueditor/images/',
                          filePath='courses/ueditor/files/',
                          upload_settings={'imageMaxSize': 1204000}, settings={}, command=None, blank=True, default='')
    image = models.ImageField(verbose_name='封面图', upload_to='courses/%Y/%m', max_length=100)
    is_banner = models.BooleanField(verbose_name='是否广告位', default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name

    def lesson_nums(self):
        return self.lesson_set.all().count()


@python_2_unicode_compatible
class Lesson(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='课程')
    name = models.CharField(verbose_name='章节', max_length=100)
    learn_times = models.PositiveIntegerField(verbose_name='章节时长/分', default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '课程章节'
        verbose_name_plural = verbose_name


@python_2_unicode_compatible
class Video(BaseModel):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, verbose_name='课程')
    name = models.CharField(verbose_name='视频名', max_length=100)
    learn_times = models.PositiveIntegerField(verbose_name='视频时长/分', default=0)
    url = models.CharField(verbose_name='视频链接', max_length=1000)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '课程视频'
        verbose_name_plural = verbose_name


@python_2_unicode_compatible
class CourseResource(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='课程')
    name = models.CharField(verbose_name='资源名', max_length=100)
    file = models.FileField(verbose_name='资源文件', upload_to='courses/resourse/%Y/%m', max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '课程资源'
        verbose_name_plural = verbose_name


@python_2_unicode_compatible
class CourseTag(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='课程')
    tag = models.CharField(verbose_name='标签', max_length=100)

    def __str__(self):
        return self.tag

    class Meta:
        verbose_name = '课程标签'
        verbose_name_plural = verbose_name

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}慕学在线网{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static  'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static  'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static  'css/style.css' %}">
    {% block css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>服务电话：<b>33333333</b></p></div>
                    <!--登录后跳转-->
                    {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}<img class="down fr"
                                                                    src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                                    </dt>
                                    <dd>
                                        <h2>django</h2>
                                        <p>{{ request.user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}
                </div>
            </div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>


            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li class="active"><a href="{% url 'index' %}">首页</a></li>
                            <li>
                                <a href="{% url 'course:list' %}">
                                    公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'org:teachers' %}">授课教师</a>
                            </li>
                            <li><a href="{% url 'org:list' %}">授课机构</a></li>
                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </header>
</section>

{% block bread %}
{% endblock %}

{% block content %}
{% endblock %}

<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
                <li class="code"><img src="{% static 'images/code.jpg' %}"/>
                    <p class="center">扫描关注微信</p></li>
                <li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/>
                    <p class="tell">33333333</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
            <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script src="{% static 'js/plugins/laydate/laydate.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>
{% block js %}{% endblock %}
</body>
</html>

templates/course-video.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/muke/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/css/muke/course/learn-less.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/css/muke/course/common-less.css' %}">
{% endblock %}
{% block content %}
    <div id="main">
        <div class="course-infos">
            <div class="w pr">
                <div style="height: 15px" class="path">
                </div>
                <div class="hd">
                    <h2 class="l">{{ course_detail.name }}</h2>
                </div>
                <div class="statics clearfix">
                    <div class="static-item ">
                        <span class="meta-value"><strong>{{ course_detail.get_degree_display }}</strong></span>
                        <span class="meta">难度</span>
                        <em></em>
                    </div>
                    <div class="static-item static-time">
                        <span class="meta-value">{{ course_detail.learn_times }}分钟</span>
                        <span class="meta">时长</span>
                        <em></em>
                    </div>
                    <div class="static-item">
                        <span class="meta-value"><strong>{{ course_detail.click_nums }}</strong></span>
                        <span class="meta">学习人数</span>
                        <em></em>
                    </div>
                </div>
            </div>
        </div>
        <div class="course-info-main clearfix w has-progress">

            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active active" id="learnOn"
                                       href="{% url 'course:lesson' course_detail.id %}"><span>章节</span></a></li>
                                <li><a id="commentOn" class="" href="{% url 'course:comment' course_detail.id %}"><span>评论</span></a></li>
                            </ul>
                        </div>
                        <div id="notice" class="clearfix">
                            <div class="l"><strong>课程公告:</strong> <a
                                    href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a></div>
                        </div>

                        <div class="mod-chapters">
                            {% for lesson in course_detail.lesson_set.all %}
                                <div class="chapter chapter-active">
                                    <h3>
                                        <strong><i class="state-expand"></i>{{ lesson.name }}
                                        </strong>
                                    </h3>
                                    <ul class="video">
                                        {% for video in lesson.video_set.all %}
                                            <li>
                                                <a target="_blank"
                                                   href='{% url 'course:video' course_detail.id video.id %}'
                                                   class="J-media-item studyvideo">
                                                    {{ video.name }}
                                                    <i class="study-state"></i>
                                                </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="aside r">
                        <div class="bd">

                            <div class="box mb40">
                                <h4>资料下载</h4>
                                <ul class="downlist">
                                    {% for rescource in course_resources %}
                                        <li>
                                            <span><i class="aui-iconfont aui-icon-file">{{ rescource.name }}</i></span>
                                            <a href="{{ rescource.file.url }}" class="downcode"
                                               target="_blank" download="" data-id="274" title="">下载</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="{% url 'org:teacher_detail' course_detail.teacher.id %}" target="_blank">
                                        <img src='{{ MEDIA_URL }}{{ course_detail.teacher.image }}' width='80'
                                             height='80'/>
                                    </a>
                                    <span class="tit">
          <a href="{% url 'org:teacher_detail' course_detail.teacher.id %}"
             target="_blank">{{ course_detail.teacher.name }}</a>
        </span>
                                    <span class="job">xxx</span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>课程须知</dt>
                                        <dd class="autowrap">{{ course_detail.youneed_know }}</dd>
                                    </dl>
                                    <dl>
                                        <dt>老师告诉你能学到什么？</dt>
                                        <dd class="autowrap">{{ course_detail.teacher_tell }}</dd>
                                    </dl>
                                </div>
                            </div>


                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                                         style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">
                                            {% for related_course in related_courses %}
                                                <li class="curr">
                                                    <a href="course-detail.html" target="_blank">
                                                        <img src="{{ MEDIA_URL }}{{ related_course.image }}"
                                                             alt="{{ related_course.name }}">
                                                        <span class="name autowrap">{{ related_course.name }}</span>
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                        <ul class="other-list">
                                            <li class="curr">
                                                <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                    <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg"
                                                         alt="Java工程师">
                                                    <span class="name autowrap">Java工程师</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="clear"></div>

            </div>

        </div>
    </div>
{% endblock %}

templates/usercenter-base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}个人信息- 慕学在线网{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lq.datetimepick.css' %}"/>
    {% block css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
        <div class="header2 header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>服务电话：<b>33333333</b></p></div>
                    <!--登录后跳转-->


                    <div class="personal">
                        <dl class="user fr">
                            <dd>bobby<img class="down fr" src="../images/top_down.png"/></dd>
                            <dt><img width="20" height="20" src="../media/image/2016/12/default_big_14.png"/></dt>
                        </dl>
                        <div class="userdetail">
                            <dl>
                                <dt><img width="80" height="80" src="../media/image/2016/12/default_big_14.png"/></dt>
                                <dd>
                                    <h2>django</h2>
                                    <p>bobby</p>
                                </dd>
                            </dl>
                            <div class="btn">
                                <a class="personcenter fl" href="usercenter-info.html">进入个人中心</a>
                                <a class="fr" href="/logout/">退出</a>
                            </div>
                        </div>
                    </div>
                    <a href="usercenter-message.html">
                        <div class="msg-num"><span id="MsgNum">0</span></div>
                    </a>


                </div>
            </div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo2.png' %}"/></a>
                    <h1>我的慕学网</h1>
                </div>
            </div>
        </div>
    </header>
</section>


<!--crumbs start-->
{% block bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>个人信息</li>
            </ul>
        </div>
    </section>
{% endblock %}

<section>
    <div class="wp list personal_list">
        <div class="left">
            <ul>
                <li class="active2"><a href="{% url 'users:info' %}">个人资料</a></li>
                <li><a href="{% url 'users:mycourse' %}">我的课程</a></li>
                <li><a href="{% url 'users:myfav_course' %}">我的收藏</a></li>
                <li>
                    <a href="{% url 'users:mymessage' %}" style="position: relative;">
                        我的消息
                    </a>
                </li>
            </ul>
        </div>
        <div class="right">
            {% block content %}{% endblock %}
        </div>
    </div>
</section>

<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/plugins/laydate/laydate.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>
<script src='{% static 'js/plugins/jquery.upload.js' %}' type='text/javascript'></script>
<script src="{% static 'js/validate.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-user.js' %}" type="text/javascript"></script>
{% block js %}{% endblock %}
</body>
</html>

templates/usercenter-message.html
{% extends 'usercenter-base.html' %}

{% block bread %}
        <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我的消息</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的消息</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li class="active"><a href="/user/message/">个人消息</a></li>
                </ul>
            </div>
            <div class="messagelist">
                <div class="messages">
                    <div class="fr">
                        <div class="top"><span class="fl time">2016年11月6日 23:49</span><span
                                class="fr btn foldbtn"></span></div>
                        <p>
                            欢迎注册
                        </p>
                    </div>
                </div>
            </div>
            <div class="pageturn pagerright">
                <ul class="pagelist">
                    <li class="active"><a href="?page=1">1</a></li>
                </ul>
            </div>
        </div>
{% endblock %}